export const FETCH_USER = 'fetch_user'
export const CREATE_TRIP = 'create_trip'
export const FETCH_TRIPS = 'fetch_trips'
export const FETCH_TRIP = 'fetch_trip'
export const EDIT_TRIP = 'edit_trip'
export const DELETE_TRIP = 'delete_trip'
export const GET_PREDICTIONS = 'get_predictions'
export const GET_NUMBER_OF_STOPS = 'get_number_of_stops'